# Generated by Django 4.2 on 2025-06-01 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at'], 'verbose_name': 'Guruh', 'verbose_name_plural': 'Guruhlar'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='schedule',
        ),
        migrations.AddField(
            model_name='group',
            name='camera_ip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Camera IP'),
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
