# Generated by Django 4.2 on 2025-06-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_group_options_remove_group_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='camera_ip',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kamera nomi')),
                ('ip_address', models.CharField(max_length=200, verbose_name='IP manzil')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Foydalanuvchi')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parol')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Joylashuv')),
                ('active', models.BooleanField(default=True, verbose_name='Faol')),
                ('last_status', models.CharField(blank=True, max_length=50, verbose_name='Oxirgi holat')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi tekshiruv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(related_name='cameras', to='app.group', verbose_name='Guruhlar')),
            ],
            options={
                'verbose_name': 'Kamera',
                'verbose_name_plural': 'Kameralar',
                'ordering': ['name'],
            },
        ),
    ]
